### ISSUE TITLE
这是为啥

### ISSUE THREAD

**Issue by lovezm** [lkeme/BiliAuth#1]
Fatal error: Uncaught Error: Class 'Lkeme\BiliAuth' not found in /www/wwwroot/xxx.cc/bili/cookie.php:4 Stack trace: #0 {main} thrown in /www/wwwroot/xxx.cc/bili/cookie.php on line 4

**Comment by lkeme** [comment]
你怎么使用的，引入autoload.php了吗   
```php
 require './vendor/autoload.php';
```

**Comment by lovezm** [comment]
好了好了 谢谢大佬

**Comment by lovezm** [comment]
再问一个低级问题 验证码咋直接显示在页面上啊=。= 好像载入了autoload.php以后html标签就不管用了。直接显示的话全屏的又看不到cookie

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/48949733-f4ac2500-ef73-11e8-80c3-4c61d8e35628.png)
大佬 请问加载验证码和登录必须在同一页面吗
