### ISSUE TITLE
refreshToken没用

### ISSUE THREAD

**Issue by nmdx** [lkeme/BiliAuth#2]
返回确实显示成功了，不过再用checkToken检查这个accesskey的时候，有效期还是旧的。。并且实际一个月测试过这个accesskey还是会过期。。

估计哔哩自己的问题   没救

**Comment by lkeme** [comment]
这个没测试过，这个api里的登陆是用的v2版本，还是用的是字母验证码，现在B站用的是v3版本，用的是行为式验证码，可能是B站的问题，把这个功能缩水了
